# Dicionário de Dados

 **Nome**    | **Tipo No BigQuery** | **Descrição**                                                         | **Cobertura Temporal** | **Unidade De Medida** | **Contém Dados Sensíveis (LGPD)** | **Observações**                                                                                                                                                                                                       
:-----------:|:--------------------:|:---------------------------------------------------------------------:|:----------------------:|:---------------------:|:---------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:
 ano         | INT64                | Ano                                                                   | 1995 - 2021            | Ano                   | Não listado                       | Não listado                                                                                                                                                                                                           
 disciplina  | STRING               | Disciplina                                                            | 1995 - 2021            | Não listado           | Não listado                       | A tabela considera apenas as disciplinas de Língua Potuguesa (LP) e Matemática (MT) 
 localizacao | STRING               | Localização da escola                                                 | 1995 - 2021            | Não listado           | Não listado                       | Mantiveram-se apenas os totais não havendo distinções entre rural e urbana                                                                                                                                            
 media       | FLOAT64              | Média da proficiência                                                 | 1995 - 2021            | Não listado           | Não listado                       | Não listado
  rede        | STRING               | Rede Escolar                                                          | 1995 - 2021            | Não listado           | Não listado                       | Não listado                                                                                                                                                                                                           
 serie       | INT64                | Série/Ano Escolar                                                     | 1995 - 2021            | Não listado           | Não listado                       | Não listado 
 nivel_0     | FLOAT64              | Percentual de alunos que se enquadram no nível zero de aprendizagem   | 1995 - 2021            | Não listado           | Não listado                       | Não listado                                                                                                                                                                                                           
 nivel_1     | FLOAT64              | Percentual de alunos que se enquadram no nível um de aprendizagem     | 1995 - 2021            | Não listado           | Não listado                       | Não listado                                                                                                                                                                                                           
 nivel_10    | FLOAT64              | Percentual de alunos que se enquadram no nível dez de aprendizagem    | 1995 - 2021            | Não listado           | Não listado                       | Não listado                                                                                                                                                                                                           
 nivel_2     | FLOAT64              | Percentual de alunos que se enquadram no nível dois de aprendizagem   | 1995 - 2021            | Não listado           | Não listado                       | Não listado                                                                                                                                                                                                           
 nivel_3     | FLOAT64              | Percentual de alunos que se enquadram no nível três de aprendizagem   | 1995 - 2021            | Não listado           | Não listado                       | Não listado                                                                                                                                                                                                           
 nivel_4     | FLOAT64              | Percentual de alunos que se enquadram no nível quatro de aprendizagem | 1995 - 2021            | Não listado           | Não listado                       | Não listado                                                                                                                                                                                                           
 nivel_5     | FLOAT64              | Percentual de alunos que se enquadram no nível cinco de aprendizagem  | 1995 - 2021            | Não listado           | Não listado                       | Não listado                                                                                                                                                                                                           
 nivel_6     | FLOAT64              | Percentual de alunos que se enquadram no nível seis de aprendizagem   | 1995 - 2021            | Não listado           | Não listado                       | Não listado                                                                                                                                                                                                           
 nivel_7     | FLOAT64              | Percentual de alunos que se enquadram no nível sete de aprendizagem   | 1995 - 2021            | Não listado           | Não listado                       | Não listado                                                                                                                                                                                                           
 nivel_8     | FLOAT64              | Percentual de alunos que se enquadram no nível oito de aprendizagem   | 1995 - 2021            | Não listado           | Não listado                       | Não listado                                                                                                                                                                                                           
 nivel_9     | FLOAT64              | Percentual de alunos que se enquadram no nível nove de aprendizagem   | 1995 - 2021            | Não listado           | Não listado                       | Não listado

# Importando as Bibliotecas

In [1]:
# Biblioteca utilizada para carregar os dados
import pandas as pd
import basedosdados as bd

# Carregando os Dados

In [2]:
tabela_avaliacao= bd.read_table(dataset_id='br_inep_saeb',
                   table_id='brasil',
                   billing_project_id="api-ads-388816")

Downloading: 100%|█████████████████████████████████████████████████████████████| 1124/1124 [00:00<00:00, 2073.67rows/s]

# Visualizando a Tabela

In [3]:
tabela_avaliacao.head()

,ano,rede,localizacao,disciplina,serie,media,nivel_0,nivel_1,nivel_2,nivel_3,nivel_4,nivel_5,nivel_6,nivel_7,nivel_8,nivel_9,nivel_10
0,2019,estadual,total,LP,2,751.222766,4.602618,3.951387,5.985628,11.485410,17.949120,22.248559,18.728565,10.458310,4.590403,NaN,NaN
1,2019,federal,total,LP,2,777.844695,1.193606,0.402326,1.581318,3.762806,12.182706,25.344901,28.774909,15.366830,11.390597,NaN,NaN
2,2019,municipal,total,LP,2,741.635071,5.876650,5.299290,8.367580,13.820993,19.199500,20.724740,15.950030,7.151382,3.609836,NaN,NaN
3,2019,privada,total,LP,2,775.639175,0.636825,0.968077,1.990333,6.087452,13.279804,23.714790,25.898868,17.564209,9.859642,NaN,NaN
4,2019,total - estadual e municipal,total,LP,2,743.254884,5.661406,5.071565,7.965156,13.426403,18.988252,20.982185,16.419455,7.710078,3.775500,NaN,NaN

## Valores que podem ser pesquisados

* ##  Anos disponivéis:

In [4]:
# Salvando os valores cosiderados na tabela em uma lista
anos = list(tabela_avaliacao['ano'].unique())

# Ordenando a lista 
anos.sort()

# Devolvendo os valores da lista na tela
for n in anos:    # O loop for foi usado apenas para melhorar a visualização dos valores
    print(n)

1995
1997
1999
2001
2003
2005
2007
2009
2011
2013
2015
2017
2019
2021

* ##  Disciplinas disponivéis:

In [7]:
# Salvando os valores cosiderados na tabela em uma lista
disciplinas = list(tabela_avaliacao['disciplina'].unique())

# Devolvendo os valores da lista na tela
for n in disciplinas:    # O loop for foi usado apenas para melhorar a visualização dos valores
    print(n)

LP
MT

# Criando a Pesquisa

In [25]:
# Pedindo dados para o  usuário
ano = int(input("Informe o ano conforme opções acima: "))
disciplina = input("Informe a disciplinas conforme opções acima: ")
opcao = input("Informe com sim ou nao, se desejá baixar a busca: ")

# Gerando a busca, por filtragem
tabela_busca1 = tabela_avaliacao[tabela_avaliacao['ano'] == ano]

busca_final = tabela_busca1[tabela_busca1['disciplina'] == disciplina]

# Salvando ou não a pesquisa

if opcao in ['sim', 'Sim']:
    busca_final.to_excel('pesquisa_{}_{}.xlsx'.format(ano, disciplina))
    
elif opcao in ['nao', 'Nao', 'não', 'Não']:
    display(busca_final)

else:
    print("Digite apenas as opções informadas!")

Informe o ano conforme opções acima: 1995
Informe a disciplinas conforme opções acima: MT
Informe com sim ou nao, se desejá baixar a busca: nao

,ano,rede,localizacao,disciplina,serie,media,nivel_0,nivel_1,nivel_2,nivel_3,nivel_4,nivel_5,nivel_6,nivel_7,nivel_8,nivel_9,nivel_10
101,1995,estadual,total,MT,5,182.083784,4.146744,15.564952,27.525270,23.867214,15.442002,9.288081,2.585162,1.250043,0.320091,0.010440,0.000000
102,1995,federal,total,MT,5,188.331247,2.145986,13.797545,23.445166,25.613602,18.804178,10.372779,3.630039,1.531200,0.538696,0.110797,0.010012
103,1995,municipal,total,MT,5,222.240405,0.560360,5.120243,12.276950,17.389715,18.935621,16.883923,15.164341,7.503504,3.584309,1.973863,0.607172
104,1995,privada,total,MT,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,1995,total - estadual e municipal,total,MT,5,193.576897,3.120295,12.575601,23.161092,22.013308,16.441901,11.462065,6.185413,3.039828,1.254334,0.572386,0.173777
106,1995,"total - federal, estadual e municipal",total,MT,5,190.605496,2.568397,13.267772,23.322006,24.052696,17.780013,10.845039,4.737920,2.185265,0.848960,0.310919,0.081012
107,1995,"total - federal, estadual, municipal e privada",total,MT,5,190.605496,2.568397,13.267772,23.322006,24.052696,17.780013,10.845039,4.737920,2.185265,0.848960,0.310919,0.081012
275,1995,estadual,total,MT,9,242.567498,18.605699,17.984174,21.507487,19.334402,12.446537,6.229278,2.333350,0.818350,0.654079,0.086643,NaN
276,1995,federal,total,MT,9,246.281839,15.036792,16.778455,21.951650,21.099455,14.205870,6.859365,3.220472,0.720213,0.122086,0.005642,NaN
277,1995,municipal,total,MT,9,292.841389,4.188162,6.423802,8.985894,14.321384,17.142657,21.514474,15.181880,8.425436,3.254203,0.562108,NaN
278,1995,privada,total,MT,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,1995,total - estadual e municipal,total,MT,9,270.129118,10.701583,11.646439,14.642783,16.586119,15.021087,14.609070,9.377291,4.988778,2.079544,0.347307,NaN
280,1995,"total - federal, estadual e municipal",total,MT,9,253.201461,13.778871,15.289329,19.830880,19.789848,14.442417,9.108050,5.006959,1.958797,0.690069,0.104781,NaN
281,1995,"total - federal, estadual, municipal e privada",total,MT,9,253.201461,13.778871,15.289329,19.830880,19.789848,14.442417,9.108050,5.006959,1.958797,0.690069,0.104781,NaN
449,1995,estadual,total,MT,3,273.464306,15.004929,11.536266,15.513773,18.749019,17.292761,14.009854,6.875428,2.724641,0.318851,0.000000,0.000000
450,1995,federal,total,MT,3,358.787569,2.342539,5.308573,7.203151,8.647533,8.675671,28.784468,26.439692,7.747139,1.500657,0.000000,0.000000
451,1995,municipal,total,MT,3,264.253176,22.386232,13.638027,17.067084,17.236790,21.063490,8.641688,3.429056,1.702050,0.086517,0.000000,0.000000
452,1995,privada,total,MT,3,306.460281,9.964225,7.219264,10.546283,15.104340,17.983059,17.175812,14.608044,7.999449,1.050799,0.000000,0.000000
453,1995,total - estadual e municipal,total,MT,3,272.536990,15.748030,11.746308,15.669005,18.597892,17.669594,13.473379,6.531011,2.622447,0.295632,0.000000,0.000000
454,1995,"total - federal, estadual e municipal",total,MT,3,274.105837,15.504192,11.634168,15.521537,18.424565,17.512927,13.740085,6.877803,2.711715,0.316623,0.000000,0.000000
455,1995,"total - federal, estadual, municipal e privada",total,MT,3,282.013791,14.150134,10.563956,14.315490,17.619712,17.626891,14.572936,8.751683,3.993509,0.494594,0.000000,0.000000
623,1995,estadual,total,MT,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
624,1995,federal,total,MT,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,1995,municipal,total,MT,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
626,1995,privada,total,MT,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
627,1995,total - estadual e municipal,total,MT,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
628,1995,"total - federal, estadual e municipal",total,MT,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
629,1995,"total - federal, estadual, municipal e privada",total,MT,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797,1995,estadual,total,MT,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
798,1995,federal,total,MT,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
799,1995,municipal,total,MT,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
800,1995,privada,total,MT,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
801,1995,total - estadual e municipal,total,MT,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
802,1995,"total - federal, estadual e municipal",total,MT,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
803,1995,"total - federal, estadual, municipal e privada",total,MT,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN